Use numpy 2.1.1 and remove oldest-supported-numpy which is now deprec…
ComputeCanada/wheels_builder pull request #119
Opened 2024-09-17 18:37 UTC by ccoulombe

…ated

`oldest-supported-numpy` is now deprecated. This means we'll need to build with numpy 2.0 and backward compat 1.x.
https://github.com/scipy/oldest-supported-numpy/commit/23ece5a161d5957f5142991393d2ae689ee45b9d (edited)

2024-09-17 18:49 UTC, ccoulombe commented
Closes https://github.com/ComputeCanada/software-stack/issues/156

2024-09-19 12:42 UTC, mboisson requested changes
Ligne 8 à enlever
 adjust_numpy_requirements_based_on_link_info à modifier/enlever pour ne plus mettre la version minimum de numpy si numpy_build_verison >= 2

2024-09-19 12:42 UTC, mboisson commented on build_wheel.sh
> +PYTHON_DEPS_DEFAULT="numpy==2.1.1"
devrait être le module ?

2024-09-19 12:47 UTC, ccoulombe commented on build_wheel.sh
> +PYTHON_DEPS_DEFAULT="numpy==2.1.1"
Ce sera équivalent. J'avais fait cette PR avant que l'on discute de créer un module pour 2.1.1.

2024-09-23 18:48 UTC, mboisson commented on build_wheel.sh
> +			numpy_build_version=$(pip show numpy | grep -E '^Version:' | awk '{print $2}' | sed -e "s/\([0-9]\.[0-9]*\)\..*/\1/g")
```
python -c "import numpy; print(numpy.__version__)"
2.1.1
```

?

2024-09-23 18:49 UTC, mboisson commented
minor detail, otherwise LGTM.

2024-09-23 19:02 UTC, ccoulombe commented on build_wheel.sh
> +			numpy_build_version=$(pip show numpy | grep -E '^Version:' | awk '{print $2}' | sed -e "s/\([0-9]\.[0-9]*\)\..*/\1/g")
Yup, way better and clearer :
```
python -c "import numpy; print(numpy.__version__)" | grep -P -oe '\d+.\d'
```

2024-09-23 20:11 UTC, merged